version: '3.8'

services:
  chatweb-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatweb-backend-app
    ports:
      - "8086:8086"
    environment:
      - PORT=8086
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}

      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}

      - UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}
    restart: always