services:
  db:
    image: postgres:16
    container_name: chatweb-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '11111111'
      POSTGRES_DB: chatweb_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: