DO $$ BEGIN
CREATE TYPE conv_type AS ENUM ('PRIVATE', 'GROUP');
CREATE TYPE member_role AS ENUM ('ADMIN', 'MEMBER');
CREATE TYPE msg_type AS ENUM ('TEXT', 'IMAGE', 'FILE', 'VIDEO', 'SYSTEM');
CREATE TYPE delivery_status AS ENUM ('DELIVERED', 'SEEN');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) UNIQUE NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       avatar_url TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=default',
                       last_seen TIMESTAMP WITH TIME ZONE,
                       created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               type conv_type NOT NULL,
                               name VARCHAR(100),
                               created_by BIGINT REFERENCES users(id),
                               last_message_id BIGINT,
                               last_message_at TIMESTAMP WITH TIME ZONE,
                               created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT check_private_name CHECK (
                                   (type = 'PRIVATE' AND name IS NULL)
                                       OR (type = 'GROUP')
                                   )
);

CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                          sender_id BIGINT NOT NULL REFERENCES users(id),
                          content TEXT,
                          type msg_type DEFAULT 'TEXT',
                          reply_to_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
                          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          is_deleted BOOLEAN DEFAULT FALSE,
                          is_edited BOOLEAN DEFAULT FALSE,
                          deleted_at TIMESTAMP WITH TIME ZONE,
                          deleted_by BIGINT REFERENCES users(id)
);

ALTER TABLE conversations
    ADD CONSTRAINT fk_last_message
        FOREIGN KEY (last_message_id) REFERENCES messages(id) ON DELETE SET NULL;

CREATE TABLE conversation_members (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                                      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                      nickname VARCHAR(50),
                                      role member_role DEFAULT 'MEMBER',
                                      last_seen_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
                                      joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                      UNIQUE (conversation_id, user_id)
);

CREATE TABLE attachments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                             file_url TEXT NOT NULL,
                             file_type VARCHAR(50),
                             file_size BIGINT
);

CREATE TABLE message_delivery (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                                  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                  status delivery_status,
                                  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                  UNIQUE (message_id, user_id)
);

CREATE TABLE invalidated_tokens (
                                    id VARCHAR(255) PRIMARY KEY,
                                    expiry_time TIMESTAMP WITH TIME ZONE NOT NULL,
                                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_msgs_conv_id_id_desc ON messages (conversation_id, id DESC);
CREATE INDEX idx_msgs_not_deleted ON messages (conversation_id, id DESC) WHERE is_deleted = FALSE;
CREATE INDEX idx_conv_last_msg ON conversations (last_message_at DESC);
CREATE INDEX idx_member_user ON conversation_members (user_id, conversation_id);
CREATE INDEX idx_attach_msg ON attachments(message_id);